load("//bazel:defs.bzl", "crate_library", "crate_tests")

exports_files(["Cargo.toml"])

COMPILE_DATA = glob([
    "fixtures/**",
    "requirements-driver-smoke.txt",
]) + ["//:Cargo.lock"]
COMPILE_DATA += ["//crates/pgwire:tests/fixtures/test-ca.pem"]

crate_library(
    name = "gres-conformance",
    compile_data = COMPILE_DATA,
)
crate_tests(
    lib = "gres-conformance",
    compile_data = COMPILE_DATA,
    mutants = False,
)
